services:
  train-container:
    build:
      context: .
      dockerfile: nlp/dockerfile.train
    volumes:
      - ./nlp/trained_model:/app/trained_model
    command: uv run python nlp/train.py
    working_dir: /app
  inference-container:
    build:
      context: .
      dockerfile: nlp/dockerfile.inference
    ports:
      - "5000:5000"
    depends_on:
      - train-container
    volumes:
      - ./nlp/trained_model:/app/trained_model
    working_dir: /app
  realtime-container:
    build:
      context: .
      dockerfile: nlp/dockerfile.realtime
    profiles:
      - audio
    devices:
      - /dev/snd:/dev/snd # Required for accessing microphone
    environment:
      - PYTHONUNBUFFERED=1 # Ensures real-time logs
  transcribe-container:
    build:
      context: .
      dockerfile: nlp/dockerfile.transcribe
    environment:
      - PYTHONUNBUFFERED=1 # Ensures real-time logs
